### ISSUE TITLE
Prevent `@enum` from begin deleted

### ISSUE THREAD

**Issue by vabatta** [jarvisuser90/postgraphile-remove-foreign-key-fields-plugin#2]
**Is your feature request related to a problem? Please describe.**
When using the table approach to `ENUM`s (as described in https://www.graphile.org/postgraphile/enums/) the plugin will remove the key out because recognized as a foreign key. If a column (or table) is marked with `@enum`, it should be skipped.

**Describe the solution you'd like**
If a column (or table) is marked with `@enum`, it should be skipped.

**Comment by vabatta** [comment]
Any news? I've seen you did some changes on dev :)

**Comment by jarvisuser90** [comment]
> Any news? I've seen you did some changes on dev :)

Hi @vabatta. I think I have a solution but just haven't had time to test it. I'll try to get to it today or tomorrow. Please feel free to try it from the development branch if you want.

**Comment by jarvisuser90** [comment]
@vabatta Please let me know if that fixes it for you, and I'll close this issue. 👍🏼

**Comment by vabatta** [comment]
@jarvisuser90 Nope. The issue here is that `@enum` is marked on the referenced table, not the actual table that goes through the hook as `GraphQLObjectType`. Also, note that `@enum` is a smart comment rather than a smart tag, as it runs in an earlier stage introspection, you won't be going through `enum` tables with that hook. This means the condition https://github.com/jarvisuser90/postgraphile-remove-foreign-key-fields-plugin/blob/main/src/index.ts#L28-L31 is unnecessary.

From the docs
> IMPORTANT: this is one of the few places where a smart tag and a smart comment is not equivalent, this must be achieved with a smart comment since smart tags have not yet loaded at this stage in introspection.

The actual fix I can see straight away (which I have locally tested and works :) ) is to check if the referenced table in the `keyAttribute` is marked as `@enum` instead of the actual constraint.

From (https://github.com/jarvisuser90/postgraphile-remove-foreign-key-fields-plugin/blob/main/src/index.ts#L76-L79)
```ts
// Check if the foreign key is marked as an enum reference.
const isEnum = attribute.comment
  ? attribute.comment.includes("@enum")
  : false;
```

To
```ts
const { foreignClass } = constraint;
// Check if the foreign key is marked as an enum reference.
const isEnum =
  foreignClass && foreignClass.comment
  ? foreignClass.comment.includes("@enum")
  : false;
```

As a final note, we might be missing other use cases where `@enum` could be excluded; I haven't had a deeper look into it, might be worth to have a look with a proper use cases.

**Comment by jarvisuser90** [comment]
@vabatta ah, I see. I can make the changes or if you'd like, feel free to submit a pull request.

**Comment by vabatta** [comment]
@jarvisuser90 I'll fork, do the changes and some more testing. A PR will come afterwards :)

**Comment by jarvisuser90** [comment]
> @jarvisuser90 I'll fork, do the changes and some more testing. A PR will come afterwards :)

@vabatta PR done and merged. A new NPM package has been pushed.

**Comment by vabatta** [comment]
@jarvisuser90 Nice, thanks!
